#!/usr/bin/env python3
"""Compare BASF-AI/ChEmbed-prog embeddings on CPU vs Apple MPS.

Goal: help validate whether running on MPS changes embeddings (and thus retrieval) vs CPU.

- Standalone: no dataset downloads.
- Uses 5 hard-coded texts taken from our existing validation/training samples.
- Prints per-text similarity metrics and exits non-zero if differences exceed thresholds.

Usage:
  python3 scripts/compare_cpu_mps_embeddings.py

Optional:
  --model-id BASF-AI/ChEmbed-prog
  --threshold-cos 0.9999
  --threshold-max-abs 5e-3
"""

from __future__ import annotations

import argparse
import sys
from typing import List, Tuple

import numpy as np


def l2_normalize(x: np.ndarray) -> np.ndarray:
    denom = np.linalg.norm(x, axis=1, keepdims=True)
    denom = np.where(denom == 0, 1.0, denom)
    return x / denom


def encode_texts(model_id: str, device: str, texts: List[str]) -> np.ndarray:
    # Import inside so the script still prints a clean error if deps missing.
    from sentence_transformers import SentenceTransformer

    st_kwargs = {"trust_remote_code": True}
    if device != "auto":
        st_kwargs["device"] = device

    model = SentenceTransformer(model_id, **st_kwargs)

    # Normalize ourselves so we can compare apples-to-apples even if backend differs.
    emb = model.encode(
        texts,
        batch_size=8,
        convert_to_numpy=True,
        show_progress_bar=True,
        normalize_embeddings=False,
    ).astype(np.float32)

    return l2_normalize(emb).astype(np.float32)


def compare(a: np.ndarray, b: np.ndarray) -> Tuple[np.ndarray, np.ndarray, float]:
    """Return (cos_sims, max_abs_per_row, global_max_abs). Inputs must be L2-normalized."""
    cos = np.sum(a * b, axis=1)
    max_abs_per_row = np.max(np.abs(a - b), axis=1)
    global_max_abs = float(np.max(max_abs_per_row))
    return cos, max_abs_per_row, global_max_abs


TEXTS: List[str] = [
    # From /home/vector/research/chembed-eval-ui/data/training_samples.jsonl
    "Photo-induced virus elimination by injection of urchin-like nanomaterials To investigate whether nanoparticles diminish virus density, we injected the nanoparticles into the infected Phalaenopsis leaves, and collected the leaves 1, 3 and 7 days after injection. RT-PCR was performed to confirm the expression of CymMV or ORSV coat protein gene.",
    "Cell lines and cell culture The human liver hepatocellular carcinoma cell line HepG2 was obtained from the cell bank of the Chinese Academy of Sciences in Shanghai, China. Arsenic-resistant HepG2 (AsHepG2) cells were generated by treating the HepG2 cells with a low concentration of arsenic.",
    "Minimum inhibitory concentrations (MICs) MICs of CEA extract and purified compounds were determined by NCCLS microbroth dilution methods (NCCLS, 2000). The agents were dissolved in dimethyl sulfoxide (DMSO).",
    "Another significant finding arising from this work is that the dissociative chemisorption probability of CO2 on Cu(110) is largely independent of the incidence angle and follows total energy scaling, rather than normal energy scaling.",
    "To explore the feasibility of our approach, we began by investigating the photocatalytic ethylation of commercially available lepidine (1) using ethane as a C2 synthon under flow conditions.",
]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--model-id", default="BASF-AI/ChEmbed-prog")
    ap.add_argument("--threshold-cos", type=float, default=0.9999)
    ap.add_argument("--threshold-max-abs", type=float, default=5e-3)
    args = ap.parse_args()

    try:
        import torch

        mps_ok = bool(torch.backends.mps.is_available())
    except Exception as e:
        print(f"ERROR: torch import failed: {e}")
        return 2

    if not mps_ok:
        print("MPS is not available on this system. Nothing to compare.")
        return 2

    print(f"Model: {args.model_id}")
    print(f"Texts: {len(TEXTS)}")
    print("\nEncoding on CPU...")
    cpu = encode_texts(args.model_id, "cpu", TEXTS)

    print("\nEncoding on MPS...")
    mps = encode_texts(args.model_id, "mps", TEXTS)

    cos, max_abs, global_max_abs = compare(cpu, mps)

    print("\nPer-text comparison (CPU vs MPS):")
    for i, (c, ma) in enumerate(zip(cos.tolist(), max_abs.tolist()), start=1):
        print(f"  {i:02d}) cosine={c:.8f}  max_abs={ma:.6f}")

    min_cos = float(np.min(cos))
    print("\nSummary:")
    print(f"  min cosine similarity: {min_cos:.8f}")
    print(f"  global max abs diff : {global_max_abs:.6f}")

    ok = (min_cos >= args.threshold_cos) and (global_max_abs <= args.threshold_max_abs)

    print("\nConclusion:")
    if ok:
        print(
            "  PASS: Differences are within thresholds. MPS should be effectively equivalent to CPU for retrieval."
        )
        return 0

    print("  FAIL: Differences exceed thresholds.")
    print("  This does not automatically mean retrieval is wrong, but rankings may differ for borderline ties.")
    print("  If you need strict reproducibility, use --device cpu.")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
